package com.aditya.firstmultiscreenapp;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.content.Intent;
import android.view.View;
import android.widget.EditText;

public class MainActivity extends AppCompatActivity {

    public static final String AA="com.aditya.firstmultiscreenapp.ORDER";
    //we are sending key AA in our multiscreen app in our orderActivity
    //this key will carry message


    //can also write AA instead of ORDER
    // can also give AA ="order" simply but not a good practise

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    public void placeOrder(View view) {
        // on click will be handled here
        //building an intent to open another activity

        Intent intent = new Intent(this, orderActivity.class);
        EditText editText = findViewById(R.id.editText);
        EditText editText2 = findViewById(R.id.editText2);
        EditText editText3 = findViewById(R.id.editText3);
        //R is a class automatically generated by the Android development tools that contains references to all resources in your project.

        // getText() function gives text of the editText and then we are changing it to string and adding them together and giving it out on orderActivity
        String message = editText.getText().toString() + "," + editText2.getText().toString() + "," + editText3.getText().toString() + " has been placed";
        intent.putExtra(AA, message);
        startActivity(intent);
    }
}